server:
  port: 8084

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/realms/shopscale

  threads:
    virtual:
      enabled: true

  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://${REDIS_HOST}:${REDIS_PORT}"

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/${DB_NAME:notificationdb}
    username: ${DB_USER:shopscale}
    password: ${DB_PASS:shopscale}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          use_query_cache: false
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.shopscale.common.events,java.lang,java.util"
        spring.json.use.type.headers: true

    listener:
      concurrency: 3
      ack-mode: record
      missing-topics-fatal: false

  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.connectiontimeout: 3000
      mail.smtp.timeout: 3000

app:
  kafka:
    topic:
      order-cancelled: order.cancelled
  notification:
    from: noreply@shopscale.dev

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: when_authorized
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '{ "traceId": "%X{traceId:-}", "spanId": "%X{spanId:-}" } %5p [%t] %c{1}: %m%n'
  level:
    com.shopscale.notification: INFO
    org.springframework.kafka: INFO

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:discovery-service}:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20