server:
  port: 8084

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://localhost:8888

  kafka:
    bootstrap-servers: localhost:9092   # change to kafka:9092 in Docker
    consumer:
      group-id: notification-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.shopscale.common.events.OrderPlacedEvent
        spring.json.trusted.packages: "*"

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

logging:
  level:
    root: INFO