server:
  port: 8081

spring:
  application:
    name: product-service

  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:config-server}:8888

  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/realms/shopscale

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongodb:27017/productdb}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:discovery-service}:8761/eureka/

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"